.TH "xmmeec" "1" "0.1.1" "Pozsar Zsolt" "Environment characteristics editor"
.SH "NAME"
.LP 
XMMEEC \- Environment characteristics editor
.SH "SYNTAX"
.LP
xmmeec [-h | --help | -v | --version]
.br 
.SH OPTIONS
.TP
.B \-h \-\-help
Write useable parameters.
.TP
.B \-v \-\-version
Write version and build information.
.br
.SH "DESCRIPTION"
.LP 
It is an remote editor for environment characteristics configuration
file of MM3D (>v0.3) and MM5D growing house controllers.
.br
This program is free software: you can redistribute it and/or modify it
under the terms of the European Union Public License 1.1 version.
.br
.SH "FILE"
.TP
.B /etc/xmmeec.ini
configuration file
.TP
.B /usr/local/etc/xmmeec.ini
configuration file
.TP
.B ~/.config/xmmeec/xmmeec.ini
user's configuration file
.B ~/.cache/xmmeec/xmmeec.tmp
temporary file
.TP
.br
.SH "AUTHOR"
.LP 
Pozsar Zsolt
.br
Web:    <http://www.szerafingomba.hu/softwares/>
.br
E-mail: <pozsar.zsolt@szerafingomba.hu>

