.TH "xmmeec" "1" "0.2" "Pozsár Zsolt" "Environment characteristic editor"
.SH "NAME"
.LP 
XMMEEC \- Environment characteristic editor
.SH "SYNTAX"
.LP
\fBxmmeec\fP [-h | --help | -v | --version]
.br 
.SH "OPTIONS"
.TP
.B \-h \-\-help
Write useable parameters.
.TP
.B \-v \-\-version
Write version and build information.
.br
.SH "DESCRIPTION"
.LP 
It is an remote editor for environment characteristic configuration
of MM3D (>v0.3), MM5D and MM8D growing house controllers.
.br
This program is free software: you can redistribute it and/or modify it
under the terms of the European Union Public License 1.1 version.
.br
.SH "FILE"
.TP
\fI/etc/xmmeec.ini\fR or \fI/usr/local/etc/xmmeec.ini\fR
configuration file
.TP
\fI~/.config/xmmeec/xmmeec.ini\fR
user's configuration file
.TP
\fI~/.cache/xmmeec/xmmeec.tmp\fR
temporary file
.br
.SH "AUTHOR"
Pozsár Zsolt \fIpozsar.zsolt@szerafingomba.hu\fR
